version: "3.3"
name: paper-summariser
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
  api:
    build: ./retriever/
    ports:
      - "9000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
  web:
    build: ./web/
    ports:
      - "4200:4200"
    depends_on:
      - api


volumes:
  ollama:
    driver: local
