version: "3.8"
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  api:
    build: ./retriever/
    ports:
      - "8000:8000"
    depends_on:
      - ollama
  web:
    build: ./web/
    ports:
      - "4200:4200"
    depends_on:
      - api


volumes:
  ollama:
    driver: local
